/*
This program will generate three random points ona circle centered at (0,0). The radius will be 40 and the program will display
three angles ina trianlge formed by these points. Note random angle will be from 0 and 2PI.
random point will be generated by radius * cos(angle) for X and radius * sin(angle) for Y.
Nicholas Perez.
*/

public class RandomPoints {
	public static void main(String [] args) {

		//creating variables for radius and x and y points
		double radius = 40.0;
		double angle = Math.random() * 360;

		double x = radius * Math.cos( angle * Math.PI / 180 );
		double y = radius * Math.sin( angle * Math.PI / 180 );

		double angle2 = Math.random() * 360;
		double x1 = radius * Math.cos( angle2 * Math.PI / 180 ); 
		double y1 = radius * Math.sin( angle2 * Math.PI / 180 );	
		
		double angle3 = Math.random() * 360;
		double x2 = radius * Math.cos( angle3 * Math.PI / 180 ); 
		double y2 = radius * Math.sin( angle3 * Math.PI / 180 );

		System.out.println("The random poins are below.");
		System.out.println("(" + x + "," + y + ")" );
		System.out.println("(" + x1 + "," + y1 + ")" );
		System.out.println("(" + x2 + "," + y2 + ")" );
	}
}
